vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        logo_image:
            uri_prefix: /uploads/logo
            upload_destination: '%kernel.project_dir%/public/uploads/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    
    metadata :
        file_cache :
            dir: '%kernel.build_dir%/vich_uploader'